### ISSUE TITLE
您好, zsh 主题和配色能给一份?  谢了

### ISSUE THREAD

**Issue by Norvon** [jeasonstudio/git-hook-996#1]

**Comment by jeasonstudio** [comment]
没想到大家都对我的终端配色这么感兴趣，以下是我的配置 @Norvon ：
* 依赖：`item2`, `zsh`, `oh-my-zsh`
* item2 主题: Dracula [https://draculatheme.com/iterm/](https://draculatheme.com/iterm/)
* oh-my-zsh 插件：zsh-syntax-highlighting [https://github.com/zsh-users/zsh-syntax-highlighting](https://github.com/zsh-users/zsh-syntax-highlighting)
* ZSH prompt: Pure [https://github.com/sindresorhus/pure](https://github.com/sindresorhus/pure)
* Font Family: Dank Mono [https://dank.sh/](https://dank.sh/)

祝好。

**Comment by Norvon** [comment]
嗯嗯,  谢了
